<?php

namespace App\Service\Invoice;

use App\Entity\Client\Client;
use App\Enum\Invoice\InvoicePaymentMethod;
use App\Enum\Invoice\InvoiceType;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Twig\Environment;
use App\Entity\Invoice\Invoice;
use App\Entity\Core\Setting;
use App\Entity\Invoice\InvoiceItem;
use App\Service\Invoice\Wkhtml2pdfService;
use Doctrine\ORM\EntityManagerInterface;
use App\Service\Invoice\PriceTransformationService;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class InvoiceService
{

    const FOOTER_TEXT = 'Generated by DS Module System - https://www.dsmodulesystem.com';

    public function __construct(
        private Environment $twig,
        private EntityManagerInterface $em,
        private ParameterBagInterface $parameterBag,
        private PriceTransformationService $priceTransformationService,
        private Wkhtml2pdfService $wkhtml2pdfService,
        private UrlGeneratorInterface $router
    ) {}
    public function copyInvoice(Invoice $invoice): Invoice
    {
        $newInvoice = new Invoice();

        return $newInvoice;
    }

    public function getData(Invoice $invoice)
    {
        $invoiceItems = $this->em->getRepository(InvoiceItem::class)->findBy(['invoice' => $invoice]);

        $data = [];

        $invoiceClient = $invoice->getClient();

        $client = [
            'name' => '',
            'vat' => '',
            'eek' => '',
            'address' => '',
            'responsiblePerson' => '',
            'countryCode' => '',
        ];

        if ($invoiceClient instanceof Client) {
            $client = [
                'name' => $invoice->getName(),
                'vat' => $invoice->getVat() ? $invoice->getVat() : '',
                'eek' => $invoice->getEek() ? $invoice->getEek() : '',
                'address' => $invoice->getAddress() ? $invoice->getAddress() : '',
                'responsiblePerson' => $invoice->getResponsiblePerson() ? $invoice->getResponsiblePerson() : '',
                'countryCode' => $invoiceClient->getCountryCode(),
                'clientNumber' => $invoiceClient->getClientNumber(),

            ];
        }
        // $client = [
        //     'address' => '',
        //     'city' => '',
        //     'name' => '',
        //     // 'company' =>
        //     'ddsNumber' => '',
        //     'eik' => '',
        //     'egn' => '',
        //     'mol' => '',
        //     'molEn' => '',
        // ];

        // if ($invoiceClient instanceof Client) {
        //     $client = [
        //         'address' => $invoice->getAddress(),
        //         'name' => $invoice->getName(),
        //         'ddsNumber' => $invoice->getVat(),
        //         'eik' => $invoice->getEek(),
        //         'mol' => $invoice->getResponsiblePerson() ? $invoice->getResponsiblePerson() : '',
        //     ];
        // }


        $products = [];
        if ($invoiceItems) {
            foreach ($invoiceItems as $v) {
                $products[] = [
                    'name' => $v->getName(),
                    'price' => $v->getUnitPrice(),
                    'count' => $v->getQuantity(),
                    'unit' => $v->getMeasure(),
                ];
            }
        }

        $ddsOption = '';
        if (!$invoice->getDdsOption()->name == 'WithDds') {
            $ddsOption = $invoice->getDdsOption();
        }

        $companySettings = $this->em->getRepository(Setting::class)->findOneBy(['property' => 'company_info']);
        $logo = '';
        if (isset($companySettings->getValue()['companyLogo'])) {
            $logo = $companySettings->getValue()['companyLogo'];
        }
        $logoPath = '/invoice/setting_files/' . $logo;
        $logoFullPath = $this->parameterBag->get('kernel.project_dir') . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR . $logoPath;
        $image = '';
        $imageExtension = isset(explode('.', $logoPath)[1]) ? explode('.', $logoPath)[1] : '';

        if (!empty($logo) && realpath($logoFullPath)) {
            try {
                $image = "data:image/{$imageExtension};base64," . base64_encode(\file_get_contents($logoFullPath));
            } catch (\Exception $e) {
            }
        }

        $data = [
            'client' => $client,
            'company' => $companySettings,
            'invoice' => $invoice,
            'products' => $products,
            'totalSum' => $invoice->getTotalPrice(),
            'ddsTotalSum' => $invoice->getDdsPrice(),
            'paymentMethod' => $invoice->getPaymentMethod(),
            'textPrice' => $this->priceTransformationService->number2currency($invoice->getTotalPrice(), 'BGN'),
            'ddsPercent' => $invoice->getDdsPercentage(),
            'taxBasePrice' => $invoice->getTaxBasePrice(),
            'ddsOption' => $ddsOption,
            'image' =>  $image
        ];

        return $data;
    }


    public function createInvoiceFile(Invoice $invoice, $isOriginal, $isCopy)
    {
        $data = $this->getData($invoice);

        $type = [];
        if ($isOriginal !== false) {
            $type[] = 'original';
        }
        if ($isCopy !== false) {
            $type[] = 'copy';
        }
        $data['printTypes'] = $type;

        $html = $this->twig->render('invoice/template.html.twig', $data);
        $this->wkhtml2pdfService->setExtraArg('--footer-font-size "7" --footer-font-name "Verdana" --footer-right [page]/[topage] --footer-left "' . self::FOOTER_TEXT . '" '/* . $footerHTML*/);

        return $this->wkhtml2pdfService->savePdf($html);
    }


    public function previewInvoiceFile(Invoice $invoice, $isInvoiceCopy = false)
    {
        $data = $this->getData($invoice);
        $data['isInvoiceCopy'] = $isInvoiceCopy;
        return $this->twig->render('invoice/template.html.twig', $data);
    }

    public function getTextByVersion1(Invoice $invoice): string
    {
        $text = '1';
        if ($invoice->getType() == InvoiceType::Invoice) {
            $text .= '#1';
        } elseif ($invoice->getType() == InvoiceType::CreditInvoice) {
            $text .= '#2';
        } elseif ($invoice->getType() == InvoiceType::DebitInvoice) {
            $text .= '#3';
        } else {
            $text .= '#NA';
        }

        $text .= '#' . $invoice->getNumber();
        $text .= '#1';

        $companySettings = $this->em->getRepository(Setting::class)->findOneBy(['property' => 'company_info']);

        if ($companySettings->getValue()['eek']) {
            $text .= '|BG|' . $companySettings->getValue()['eek'];
        } else {
            $text .= '#NA';
        }

        $invoiceClient = $invoice->getClient();

        if ($invoiceClient instanceof Client) {
            $text .= '#1';
            if ($invoiceClient->getEek()) {
                $text .= '|BG|' . $invoiceClient->getEek();
            } else {
                $text .= '#NA';
            }
        }

        $text .= '#' . $invoice->getIssueDate()->format('Y-m-d');

        $text .= '#' . $invoice->getDdsPrice();
        $text .= '#' . $invoice->getTotalPrice();

        if ($invoice->getPaymentMethod() === InvoicePaymentMethod::Bank) {
            $text .= '#1';
        } else {
            $text .= '#NA';
        }
        $text .= '#BGN';


        return $text;
    }

    // public function checkForValidInvoiceNumberAndDate(Invoice $invoice): bool
    // {
    //     $isValid = false;
    //     // dd($invoice);
    //     if($invoice->getNumber()) {
    //         $previousInvoice = $this->em->getRepository(Invoice::class)->getPreviousInvoiceByNumber($invoice->getNumber());
    //         $nextInvoice = $this->em->getRepository(Invoice::class)->getNextInvoiceByNumber($invoice->getNumber());
    //        dd($nextInvoice);
    //         if($previousInvoice !== null && $nextInvoice !== null && $previousInvoice->getIssueDate() <= $invoice->getIssueDate() && $invoice->getIssueDate() <= $nextInvoice->getIssueDate()) {
    //             $isValid = true;
    //         } elseif ($nextInvoice === null && $previousInvoice !== null && $previousInvoice->getIssueDate() <= $invoice->getIssueDate()) {
    //             $isValid = true;
    //         } elseif ($previousInvoice === null && $nextInvoice !== null && $invoice->getIssueDate() <= $nextInvoice->getIssueDate()) {
    //             $isValid = true;
    //         } elseif ($previousInvoice === null && $nextInvoice === null) {
    //             $isValid = true;
    //         }
    //     }

    //     return $isValid;
    // }
    public function checkForValidInvoiceNumberAndDate(Invoice $invoice): bool
    {
        if (!$invoice->getNumber() || !$invoice->getType()) {
            return false;
        }

        $repo = $this->em->getRepository(Invoice::class);

        $previousInvoice = $repo->getPreviousInvoiceByNumberAndType(
            $invoice->getNumber(),
            $invoice->getType()
        );

        $nextInvoice = $repo->getNextInvoiceByNumberAndType(
            $invoice->getNumber(),
            $invoice->getType()
        );

        $issueDate = $invoice->getIssueDate();

        if (!$issueDate) {
            return false;
        }

        // No neighbors → always valid
        if ($previousInvoice === null && $nextInvoice === null) {
            return true;
        }

        // Valid only if date is between neighbors
        if (
            ($previousInvoice === null || $previousInvoice->getIssueDate() <= $issueDate)
            &&
            ($nextInvoice === null || $issueDate <= $nextInvoice->getIssueDate())
        ) {
            return true;
        }

        return false;
    }

    public function setValidNumberAndDateByKind(Invoice $invoice): void
    {
        //
        // 1. Automatically set required dates if not provided
        //
        $now = new \DateTimeImmutable();

        if ($invoice->getIssueDate() === null) {
            $invoice->setIssueDate($now);
        }

        if ($invoice->getTaxDate() === null) {
            $invoice->setTaxDate($invoice->getIssueDate());
        }

        if ($invoice->getCreatedAt() === null) {
            $invoice->setCreatedAt($now);
        }

        //
        // 2. If number already provided → validate uniqueness only
        //
        if ($invoice->getNumber() !== null && $invoice->getNumber() !== '') {

            $existing = $this->em
                ->getRepository(Invoice::class)
                ->findOneBy([
                    'type' => $invoice->getType(),
                    'number' => $invoice->getNumber(),
                ]);

            if ($existing && $existing->getId() !== $invoice->getId()) {
                throw new \RuntimeException(
                    sprintf(
                        'Number "%s" already exists for "%s".',
                        $invoice->getNumber(),
                        $invoice->getType()->label()
                    )
                );
            }

            return; // number is manually set → done
        }

        //
        // 3. Auto-generate the next number for this type
        //
        $nextNumber = $this->getNextNumberForType($invoice->getType());
        $invoice->setNumber($nextNumber);
    }

    private function getNextNumberForType(InvoiceType $type): int
    {
        $qb = $this->em->createQueryBuilder();

        $qb->select('MAX(i.number)')
            ->from(Invoice::class, 'i')
            ->where('i.type = :type')
            ->setParameter('type', $type->value);

        $max = $qb->getQuery()->getSingleScalarResult();

        return $max ? ((int)$max + 1) : 1;
    }
}
